services:
  node:
    build: infra/node/dev
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - BASE_EXTERNAL_URL=https://ondang-media.s3.us-east-1.amazonaws.com
    entrypoint: tail -f /dev/null
