services:
  node:
    build: infra/node/dev
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - .:/app/croppix
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    entrypoint: tail -f /dev/null
